export const CREATE_APPLICATION_ATTEMPT = 'CREATE_APPLICATION_ATTEMPT';
export const CREATE_APPLICATION_SUCCESS = 'CREATE_APPLICATION_SUCCESS';
export const CREATE_APPLICATION_FAIL = 'CREATE_APPLICATION_FAIL';
export const CREATE_APPLICATION_SET_VALUE = 'CREATE_APPLICATION_SET_VALUE';
