//  Create
export const CREATE_APPLICATION_ATTEMPT = 'CREATE_APPLICATION_ATTEMPT';
export const CREATE_APPLICATION_SUCCESS = 'CREATE_APPLICATION_SUCCESS';
export const CREATE_APPLICATION_FAIL = 'CREATE_APPLICATION_FAIL';
export const CREATE_APPLICATION_SET_VALUE = 'CREATE_APPLICATION_SET_VALUE';

//  Get
export const GET_APPLICATION_ATTEMPT = 'GET_APPLICATION_ATTEMPT';
export const GET_APPLICATION_SUCCESS = 'GET_APPLICATION_SUCCESS';
export const GET_APPLICATION_FAIL = 'GET_APPLICATION_FAIL';
