export const CREATE_CATEGORIES_ATTEMPT = 'CREATE_CATEGORIES_ATTEMPT';
export const CREATE_CATEGORIES_SUCCESS = 'CREATE_CATEGORIES_SUCCESS';
export const CREATE_CATEGORIES_FAIL = 'CREATE_CATEGORIES_FAIL';
export const CREATE_CATEGORIES_SET_VALUE = 'CREATE_CATEGORIES_SET_VALUE';
