//  Create
export const CREATE_JOB_ATTEMPT = 'CREATE_JOB_ATTEMPT';
export const CREATE_JOB_SUCCESS = 'CREATE_JOB_SUCCESS';
export const CREATE_JOB_FAIL = 'CREATE_JOB_FAIL';
export const CREATE_JOB_SET_VALUE = 'CREATE_JOB_SET_VALUE';

//  Get
export const GET_JOBS_ATTEMPT = 'GET_JOBS_ATTEMPT';
export const GET_JOBS_SUCCESS = 'GET_JOBS_SUCCESS';
export const GET_JOBS_FAIL = 'GET_JOBS_FAIL';
