export const CREATE_JOB_ATTEMPT = 'CREATE_JOB_ATTEMPT';
export const CREATE_JOB_SUCCESS = 'CREATE_JOB_SUCCESS';
export const CREATE_JOB_FAIL = 'CREATE_JOB_FAIL';
export const CREATE_JOB_SET_VALUE = 'CREATE_JOB_SET_VALUE';
